version: "3"
services:

  freshrss-db:
    image: postgres:12-alpine
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-freshrss}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-freshrss}
      POSTGRES_DB: ${POSTGRES_DB:-freshrss}

  freshrss-app:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:${EXPOSED_PORT:-8080}:80"
    depends_on:
      - freshrss-db
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/20'

  go-rss-hub:
    build:
      context: .
    image: hibare/go-rss-hub
    container_name: go-rss-hub
    hostname: go-rss-hub
    environment:
      - LISTEN_ADDR=0.0.0.0
    ports:
      - "127.0.0.1:5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"

volumes:
  db: null
  data: null
  extensions: null
